In [50]:
# libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib as matplot
import seaborn as sns
import os
import sqlite3
%matplotlib inline
import plotly.express as px
from plotly import graph_objs as go
import plotly.figure_factory as ff
from time import gmtime, strftime

# Model
# Compare the Logistic Regression Model V.S. Base Rate Model V.S. Random Forest Model
from sklearn.metrics import roc_auc_score
from sklearn.metrics import classification_report
from sklearn.ensemble import RandomForestClassifier

from sklearn.model_selection import train_test_split
import sklearn.metrics as metrics
from sklearn.metrics import mean_absolute_error

from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score, confusion_matrix, precision_recall_curve
from sklearn.metrics import roc_curve, ConfusionMatrixDisplay
from sklearn import metrics

from sklearn import model_selection
import torch.nn as nn

import warnings
warnings.filterwarnings("ignore")

import toolkit as tool

import os

os.system('date')

ter 12 dez 2023 17:03:09 -03


0

### Objective

The data is for company X which is trying to control attrition. There are two sets of data: “Existing employees” and “Employees who have left”. Following attributes are available for every employee.
 - Satisfaction Level
 - Last evaluation
 - Number of projects
 - Average monthly hours
 - Time spent at the company
 - Whether they have had a work accident
 - Whether they have had a promotion in the last 5 years
 - Departments (column sales)
 - Salary
 - Whether the employee has left

In [51]:
# loading dataset.
df = pd.read_csv('../datasets/HR_COM1_tomodel.csv')
df.head(100)

Emp ID  satisfaction  evaluation  projectCount  averageMonthlyHours  \
0        1          0.38        0.53             2                  157   
1        2          0.80        0.86             5                  262   
2        3          0.11        0.88             7                  272   
3        4          0.72        0.87             5                  223   
4        5          0.37        0.52             2                  159   
..     ...           ...         ...           ...                  ...   
95      96          0.37        0.51             2                  155   
96      97          0.10        0.77             6                  265   
97      98          0.10        0.84             6                  279   
98      99          0.11        0.97             6                  284   
99     100          0.90        1.00             5                  221   

    yearsAtCompany  workAccident  turnover  promotion  dept  salary  
0                3             0         1          0     7       1  
1                6             0         1          0     7       2  
2                4             0         1          0     7       2  
3                5             0         1          0     7       1  
4                3             0         1          0     7       1  
..             ...           ...       ...        ...   ...     ...  
95               3             0         1          0     7       1  
96               4             0         1          0     7       1  
97               4             0         1          0     7       1  
98               4             0         1          0     7       1  
99               6             0         1          0     7       2  

[100 rows x 11 columns]

In [52]:
print(df['dept'].value_counts(normalize=True).map('{:.2%}'.format))

7    27.60%
9    18.13%
8    14.86%
0     8.18%
6     6.01%
5     5.72%
1     5.25%
2     5.11%
3     4.93%
4     4.20%
Name: dept, dtype: object


In [53]:
df.promotion.min()

0

In [54]:
shape_rows = df.shape[0]
shape_columns = df.shape[1]

print(f'Dataset rows = {shape_rows} and columns = {shape_columns}.')

Dataset rows = 14999 and columns = 11.


### X and y 

In [55]:
# Set the input X to the K-Means.
X = df.drop(columns=['turnover', 'Emp ID'])
y = df['turnover']

In [56]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.1, random_state=123, stratify=y, shuffle = True)

### Modeling

In [57]:
os.system('date')

ter 12 dez 2023 17:03:09 -03


0

In [58]:
# Set the input X to the K-Means.
X = df.drop(columns=['turnover', 'Emp ID'])
y = df['turnover']

X = X.to_numpy()
y = y.to_numpy()

In [59]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.15, random_state=123, stratify=y, shuffle = True)

dimX = X_train.shape[1]

In [60]:
import numpy as np
import torch
from torch.utils.data import Dataset, DataLoader
class Data(Dataset):
  def __init__(self, X_train, y_train):
    # need to convert float64 to float32 else 
    # will get the following error
    # RuntimeError: expected scalar type Double but found Float
    self.X = torch.from_numpy(X_train.astype(np.float32))
    # need to convert float64 to Long else 
    # will get the following error
    # RuntimeError: expected scalar type Long but found Float
    self.y = torch.from_numpy(y_train).type(torch.LongTensor)
    self.len = self.X.shape[0]
  
  def __getitem__(self, index):
    return self.X[index], self.y[index]
  def __len__(self):
    return self.len

In [61]:
# number of features (len of X cols)
input_dim = dimX

# number of hidden layers
hidden_layers = 25

# number of classes (unique of y)
output_dim = 2

class Network(nn.Module):
  def __init__(self):
    super(Network, self).__init__()
    self.linear1 = nn.Linear(input_dim, hidden_layers)
    self.linear2 = nn.Linear(hidden_layers, output_dim)
  def forward(self, x):
    x = torch.sigmoid(self.linear1(x))
    x = self.linear2(x)
    return x

In [62]:
traindata = Data(X_train, y_train)

In [63]:
batch_size = 4
trainloader = DataLoader(traindata, batch_size=batch_size, 
                         shuffle=True, num_workers=2)

In [64]:
import torch.nn as nn
# number of features (len of X cols)
input_dim = dimX
# number of hidden layers
hidden_layers = 25
# number of classes (unique of y)
output_dim = 2

class Network(nn.Module):
  def __init__(self):
    super(Network, self).__init__()
    self.linear1 = nn.Linear(input_dim, hidden_layers)
    self.linear2 = nn.Linear(hidden_layers, output_dim)
  def forward(self, x):
    x = torch.sigmoid(self.linear1(x))
    x = self.linear2(x)
    return x

In [65]:
clf = Network()

In [66]:
print(clf.parameters)

<bound method Module.parameters of Network(
  (linear1): Linear(in_features=9, out_features=25, bias=True)
  (linear2): Linear(in_features=25, out_features=2, bias=True)
)>


In [67]:
criterion = nn.CrossEntropyLoss()
optimizer = torch.optim.SGD(clf.parameters(), lr=0.1)

In [68]:
epochs = 2

for epoch in range(epochs):
  running_loss = 0.0
  for i, data in enumerate(trainloader, 0):
    inputs, labels = data
    # set optimizer to zero grad to remove previous epoch gradients
    optimizer.zero_grad()
    # forward propagation
    outputs = clf(inputs)
    loss = criterion(outputs, labels)
    # backward propagation
    loss.backward()
    # optimize
    optimizer.step()
    running_loss += loss.item()
  # display statistics
  print(f'[{epoch + 1}, {i + 1:5d}] loss: {running_loss / 2000:.5f}')

[1,  3188] loss: 0.94152
[2,  3188] loss: 0.93661


In [69]:
testdata = Data(X_test, y_test)
testloader = DataLoader(testdata, batch_size=batch_size, 
                        shuffle=True, num_workers=2)

In [70]:
dataiter = iter(testloader)
data = next(dataiter)
data

[tensor([[  0.6300,   0.6400,   4.0000, 178.0000,   3.0000,   0.0000,   0.0000,
            6.0000,   1.0000],
         [  0.4400,   0.6700,   3.0000, 113.0000,   2.0000,   0.0000,   0.0000,
            8.0000,   1.0000],
         [  0.6600,   0.6500,   3.0000, 196.0000,   3.0000,   1.0000,   0.0000,
            9.0000,   1.0000],
         [  0.6400,   0.6300,   3.0000, 156.0000,   6.0000,   1.0000,   0.0000,
            8.0000,   1.0000]]),
 tensor([0, 0, 0, 0])]

In [71]:
print(labels)

tensor([0])


In [72]:
outputs = clf(inputs)
__, predicted = torch.max(outputs, 1)
print(predicted)

tensor([0])


In [73]:
correct, total = 0, 0
# no need to calculate gradients during inference
with torch.no_grad():
  for data in testloader:
    inputs, labels = data
    # calculate output by running through the network
    outputs = clf(inputs)
    # get the predictions
    __, predicted = torch.max(outputs.data, 1)
    # update results
    total += labels.size(0)
    correct += (predicted == labels).sum().item()
print(f'Accuracy of the network on the {len(testdata)} test data: {100 * correct // total} %')

Accuracy of the network on the 2250 test data: 76 %
